spring:
  datasource:
    username: postgres
    password: shox96shox
    url: jdbc:postgresql://localhost:5432/news
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
server:
  port: 7933
